### ISSUE TITLE
[Suggestion]: Config Option to Disable Item Rotation

### ISSUE THREAD

**Issue by Blunder-G** [Fuzss/visualworkbench#30] opened 2023-03-25 11:00 UTC
### Suggestion (Required)

I don't like the items I put on the desk to return with me. It would be much better if they stayed as I put them instead. So a config option to disable item rotation would be neat

**Comment by Fuzss** [comment] 2023-03-25 11:45
Duplicate of #19 .

**Closed by Fuzss** 2023-03-25 11:45 UTC
Labels: enhancement
