### ISSUE TITLE
[Bug]: Conflict with Sophisticated backpacks

### ISSUE THREAD

**Issue by Lagnos69** [Fuzss/visualworkbench#23] opened 2023-01-09 10:13 UTC
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

40.2.20 

### Mod Version (Required)

3.3.0

### Notes (Required)

when using the sophisticated backpacks mod and visual workbenches at the same time, the crafting upgrade you can put on the backpack that allows you to craft on the go no longer works as it closes upon interacting with it
I love these two mods is there any hope for a compatibility patch?

**Comment by Dojando98** [comment] 2023-01-09 14:41
Same here :/ 
And since we play on a server, we apparently can not disable Visual Workbench without crashing it. ;-;

**Comment by Fuzss** [comment] 2023-01-09 15:30
Please attach the latest.log file.

**Comment by Fuzss** [comment] 2023-01-09 18:59
I did some testing and was unable to reproduce your issue at all with a minimal set of mods and the latest version on 1.18.2.

What I did find was the crafting tab closing after cheating items in from JEI, but that's completely unrelated to Visual Workbench.

Please make sure to also test with a minimal set of mods, to verify Visual Workbench is actually involved in this issue. Also if possible please provide a video clip showcasing the issue.

**Comment by Fuzss** [comment] 2023-01-09 18:59
Also this report looks a lot like this: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/665

**Comment by Lagnos69** [comment] 2023-01-09 19:44
yeah, I did some testing again with minimal mods, even included some that I thought would contribute to the issue, nothing, I actually went to P3pp3rF1y's discord and brought up the issue and a moderator of theirs helped solve the issue by removing visual workbenches, it must be something in combination that's causing this, sorry, would you like me to provide a log still?

https://user-images.githubusercontent.com/122269086/211394413-5e0b60fb-7e23-4cd3-8bb2-1d6bba095926.mp4

**Comment by Fuzss** [comment] 2023-01-09 20:38
I was able to reproduce what is shown in the video after installing the Polymorph mod. Removing Visual Workbench changed nothing, the crafting tab still closes. So it looks like this is an issue solely with the Polymorph mod.

Can you test with JUST Polymorph and Sophisticated Storage if the issue persists?

**Comment by Lagnos69** [comment] 2023-01-09 21:07
It worked with just Polymorph and Sophisticated backpacks, no issues

**Comment by Fuzss** [comment] 2023-01-16 11:25
Did some more testing, and the problematic constellations seems to be Polymorph, Sophisticated Backpacks and JEI. Having Visual Workbench or not does not change anything.

**Comment by Fuzss** [comment] 2023-03-25 11:46
See my last comment, Visual Workbench has nothing to do with this. Closing this now.

**Closed by Fuzss** 2023-03-25 11:46 UTC
Labels: bug
